"""add penalty fields

Revision ID: 219db5d9acbc
Revises: 3ec33649336e
Create Date: 2026-07-07 15:33:38.247578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219db5d9acbc'
down_revision: Union[str, Sequence[str], None] = '3ec33649336e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('penalty_status', sa.String(), nullable=True))
    op.add_column('order', sa.Column('penalty_transfer_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'penalty_transfer_ref')
    op.drop_column('order', 'penalty_status')
    # ### end Alembic commands ###
