"""add firebase_uid to users

Revision ID: 40541ea47af9
Revises: d0a9922e8e12
Create Date: 2026-07-03 01:03:35.250592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40541ea47af9'
down_revision: Union[str, Sequence[str], None] = 'd0a9922e8e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_uid', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_column('user', 'firebase_uid')
    # ### end Alembic commands ###
