"""added vendor catalog details

Revision ID: bf8ea64cd283
Revises: 5d3d1971c1cb
Create Date: 2026-07-05 22:35:47.433229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8ea64cd283'
down_revision: Union[str, Sequence[str], None] = '5d3d1971c1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vendor_location', sa.String(), nullable=True))
    op.add_column('user', sa.Column('vendor_is_open', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('vendor_cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vendor_cover_image_url')
    op.drop_column('user', 'vendor_is_open')
    op.drop_column('user', 'vendor_location')
    # ### end Alembic commands ###
