"""add vendor_bank_name

Revision ID: d06d5ab0bc29
Revises: 4cedbc662b4b
Create Date: 2026-07-06 16:55:16.061246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06d5ab0bc29'
down_revision: Union[str, Sequence[str], None] = '4cedbc662b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vendor_bank_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vendor_bank_name')
    # ### end Alembic commands ###
