"""initial schema

Revision ID: d0a9922e8e12
Revises: 
Create Date: 2026-07-02 12:27:23.395941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0a9922e8e12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('vendor', 'Student', 'admin', name='approles'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('vendor_bank_account', sa.String(), nullable=True),
    sa.Column('vendor_bank_code', sa.String(), nullable=True),
    sa.Column('transaction_pin_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('webhookEvents',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('processed', 'failed', 'duplicate', name='hookstate'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('account',
    sa.Column('dva_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('account_reference', sa.Text(), nullable=False),
    sa.Column('bank_account_number', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='accstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('dva_id'),
    sa.UniqueConstraint('account_reference')
    )
    op.create_table('order',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('escrow_hold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_status', sa.Enum('pending', 'confirmed', 'expired', 'refunded', name='orderstat'), nullable=False),
    sa.Column('qr_token', sa.Text(), nullable=False),
    sa.Column('timer_expires_at', sa.DateTime(), nullable=False),
    sa.Column('nomba_transfer_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('wallet',
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('account')
    op.drop_table('webhookEvents')
    op.drop_table('user')
    # ### end Alembic commands ###
